# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: B2CMessageSendRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Message_pb2 as Message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x42\x32\x43MessageSendRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\rMessage.proto\"H\n\x15\x42\x32\x43MessageSendRequest\x12/\n\x07message\x18\x01 \x01(\x0b\x32\x1e.AcFunDanmu.Im.Message.Messageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'B2CMessageSendRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B2CMESSAGESENDREQUEST._serialized_start=69
  _B2CMESSAGESENDREQUEST._serialized_end=141
# @@protoc_insertion_point(module_scope)
