# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: B2CMessageReceiptStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x42\x32\x43MessageReceiptStatus.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\"d\n\x17\x42\x32\x43MessageReceiptStatus\x12\x11\n\treadCount\x18\x01 \x01(\x05\x12\x13\n\x0bunreadCount\x18\x02 \x01(\x05\x12\r\n\x05seqId\x18\x03 \x01(\x03\x12\x12\n\nserverTime\x18\x04 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'B2CMessageReceiptStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B2CMESSAGERECEIPTSTATUS._serialized_start=56
  _B2CMESSAGERECEIPTSTATUS._serialized_end=156
# @@protoc_insertion_point(module_scope)
