# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: B2CMessageBatchSendRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Message_pb2 as Message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n B2CMessageBatchSendRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\rMessage.proto\"M\n\x1a\x42\x32\x43MessageBatchSendRequest\x12/\n\x07message\x18\x01 \x03(\x0b\x32\x1e.AcFunDanmu.Im.Message.Messageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'B2CMessageBatchSendRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B2CMESSAGEBATCHSENDREQUEST._serialized_start=74
  _B2CMESSAGEBATCHSENDREQUEST._serialized_end=151
# @@protoc_insertion_point(module_scope)
