# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: B2CMessageReceiptCountGetResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import B2CMessageReceiptStatus_pb2 as B2CMessageReceiptStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'B2CMessageReceiptCountGetResponse.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x1d\x42\x32\x43MessageReceiptStatus.proto\"c\n!B2CMessageReceiptCountGetResponse\x12>\n\x06status\x18\x01 \x03(\x0b\x32..AcFunDanmu.Im.Message.B2CMessageReceiptStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'B2CMessageReceiptCountGetResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B2CMESSAGERECEIPTCOUNTGETRESPONSE._serialized_start=97
  _B2CMESSAGERECEIPTCOUNTGETRESPONSE._serialized_end=196
# @@protoc_insertion_point(module_scope)
