# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: B2CMessageReadAllRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x42\x32\x43MessageReadAllRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\"5\n\x18\x42\x32\x43MessageReadAllRequest\x12\x19\n\x11sessionCategoryId\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'B2CMessageReadAllRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B2CMESSAGEREADALLREQUEST._serialized_start=57
  _B2CMESSAGEREADALLREQUEST._serialized_end=110
# @@protoc_insertion_point(module_scope)
