# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelUnsubscribeResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ChannelUnsubscribeResponse.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Channel\"\x1c\n\x1a\x43hannelUnsubscribeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelUnsubscribeResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELUNSUBSCRIBERESPONSE._serialized_start=65
  _CHANNELUNSUBSCRIBERESPONSE._serialized_end=93
# @@protoc_insertion_point(module_scope)
