# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CsInformationListCard.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CsCommonInfoItem_pb2 as CsCommonInfoItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43sInformationListCard.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x16\x43sCommonInfoItem.proto\"^\n\x15\x43sInformationListCard\x12\x45\n\x0e\x63ommonInfoItem\x18\x01 \x03(\x0b\x32-.AcFunDanmu.Im.Cloud.Message.CsCommonInfoItemb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CsInformationListCard_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CSINFORMATIONLISTCARD._serialized_start=84
  _CSINFORMATIONLISTCARD._serialized_end=178
# @@protoc_insertion_point(module_scope)
