# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CsPickQuestionMessageContent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"CsPickQuestionMessageContent.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\"T\n\x1c\x43sPickQuestionMessageContent\x12\x12\n\nquestionId\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nbizContent\x18\x03 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CsPickQuestionMessageContent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CSPICKQUESTIONMESSAGECONTENT._serialized_start=67
  _CSPICKQUESTIONMESSAGECONTENT._serialized_end=151
# @@protoc_insertion_point(module_scope)
