# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupJoinRequestGetRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n GroupJoinRequestGetRequest.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\"=\n\x1aGroupJoinRequestGetRequest\x12\x0e\n\x06reqSeq\x18\x01 \x01(\x03\x12\x0f\n\x07groupId\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupJoinRequestGetRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPJOINREQUESTGETREQUEST._serialized_start=65
  _GROUPJOINREQUESTGETREQUEST._serialized_end=126
# @@protoc_insertion_point(module_scope)
