# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupSettingMemberSilence.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GroupMemberSilenceInfo_pb2 as GroupMemberSilenceInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fGroupSettingMemberSilence.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x1cGroupMemberSilenceInfo.proto\"|\n\x19GroupSettingMemberSilence\x12\x0f\n\x07muteAll\x18\x01 \x01(\x08\x12N\n\x11memberSilenceInfo\x18\x02 \x03(\x0b\x32\x33.AcFunDanmu.Im.Cloud.Message.GroupMemberSilenceInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupSettingMemberSilence_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPSETTINGMEMBERSILENCE._serialized_start=94
  _GROUPSETTINGMEMBERSILENCE._serialized_end=218
# @@protoc_insertion_point(module_scope)
