# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupSearchResult.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import User_pb2 as User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GroupSearchResult.proto\x12\x1a\x41\x63\x46unDanmu.Im.Cloud.Search\x1a\nUser.proto\"R\n\x11GroupSearchResult\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12,\n\tmatchUser\x18\x02 \x01(\x0b\x32\x19.AcFunDanmu.Im.Basic.Userb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupSearchResult_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPSEARCHRESULT._serialized_start=67
  _GROUPSEARCHRESULT._serialized_end=149
# @@protoc_insertion_point(module_scope)
