# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupMemberListGetRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SyncCookie_pb2 as SyncCookie__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fGroupMemberListGetRequest.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x10SyncCookie.proto\"a\n\x19GroupMemberListGetRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x33\n\nsyncCookie\x18\x02 \x01(\x0b\x32\x1f.AcFunDanmu.Im.Basic.SyncCookieb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupMemberListGetRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPMEMBERLISTGETREQUEST._serialized_start=82
  _GROUPMEMBERLISTGETREQUEST._serialized_end=179
# @@protoc_insertion_point(module_scope)
