# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupInviteAcceptRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GroupJoinStatus_pb2 as GroupJoinStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eGroupInviteAcceptRequest.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x15GroupJoinStatus.proto\"\x81\x01\n\x18GroupInviteAcceptRequest\x12\x10\n\x08inviteId\x18\x01 \x01(\x03\x12\x0f\n\x07groupId\x18\x02 \x01(\t\x12\x42\n\x0cinviteStatus\x18\x03 \x01(\x0e\x32,.AcFunDanmu.Im.Cloud.Message.GroupJoinStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupInviteAcceptRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPINVITEACCEPTREQUEST._serialized_start=87
  _GROUPINVITEACCEPTREQUEST._serialized_end=216
# @@protoc_insertion_point(module_scope)
