# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InputtingContent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16InputtingContent.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\"?\n\x10InputtingContent\x12\x17\n\x0f\x64isplayInterval\x18\x01 \x01(\x05\x12\x12\n\ntypingType\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InputtingContent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTTINGCONTENT._serialized_start=55
  _INPUTTINGCONTENT._serialized_end=118
# @@protoc_insertion_point(module_scope)
