# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JoinNeedPermissionType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cJoinNeedPermissionType.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message*T\n\x16JoinNeedPermissionType\x12%\n!UNKNOWN_JOIN_NEED_PERMISSION_TYPE\x10\x00\x12\x08\n\x04NONE\x10\x01\x12\t\n\x05\x41\x44MIN\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JoinNeedPermissionType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINNEEDPERMISSIONTYPE._serialized_start=61
  _JOINNEEDPERMISSIONTYPE._serialized_end=145
# @@protoc_insertion_point(module_scope)
