# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageReceiveStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aMessageReceiveStatus.proto\x12\x15\x41\x63\x46unDanmu.Im.Message*7\n\x14MessageReceiveStatus\x12\x0f\n\x0bRECEIVE_MSG\x10\x00\x12\x0e\n\nREJECT_MSG\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageReceiveStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGERECEIVESTATUS._serialized_start=53
  _MESSAGERECEIVESTATUS._serialized_end=108
# @@protoc_insertion_point(module_scope)
