# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageRangeIndexGetResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageRangeIndex_pb2 as MessageRangeIndex__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"MessageRangeIndexGetResponse.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x17MessageRangeIndex.proto\"c\n\x1cMessageRangeIndexGetResponse\x12\x43\n\x11messageRangeIndex\x18\x01 \x03(\x0b\x32(.AcFunDanmu.Im.Message.MessageRangeIndexb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageRangeIndexGetResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGERANGEINDEXGETRESPONSE._serialized_start=86
  _MESSAGERANGEINDEXGETRESPONSE._serialized_end=185
# @@protoc_insertion_point(module_scope)
