# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PassThroughType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15PassThroughType.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message*^\n\x0fPassThroughType\x12\x0f\n\x0bINVALID_PTT\x10\x00\x12\r\n\tINPUTTING\x10\x01\x12\x14\n\x10INPUTTING_CANCEL\x10\x02\x12\x15\n\x10MAX_RESERVED_PTT\x10\xe8\x07\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PassThroughType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PASSTHROUGHTYPE._serialized_start=54
  _PASSTHROUGHTYPE._serialized_end=148
# @@protoc_insertion_point(module_scope)
