# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PingRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PingRequest.proto\x12\x13\x41\x63\x46unDanmu.Im.Basic\"\x9e\x01\n\x0bPingRequest\x12;\n\x08pingType\x18\x01 \x01(\x0e\x32).AcFunDanmu.Im.Basic.PingRequest.PingType\x12\x11\n\tpingRound\x18\x02 \x01(\r\"?\n\x08PingType\x12\x0c\n\x08kInvalid\x10\x00\x12\x12\n\x0ekPriorRegister\x10\x01\x12\x11\n\rkPostRegister\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PingRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=43
  _PINGREQUEST._serialized_end=201
  _PINGREQUEST_PINGTYPE._serialized_start=138
  _PINGREQUEST_PINGTYPE._serialized_end=201
# @@protoc_insertion_point(module_scope)
