# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProfileBatchOnlineTimeResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UserOnlineStatus_pb2 as UserOnlineStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ProfileBatchOnlineTimeResponse.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Profile\x1a\x16UserOnlineStatus.proto\"i\n\x1eProfileBatchOnlineTimeResponse\x12G\n\x10userOnlineStatus\x18\x01 \x03(\x0b\x32-.AcFunDanmu.Im.Cloud.Profile.UserOnlineStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProfileBatchOnlineTimeResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROFILEBATCHONLINETIMERESPONSE._serialized_start=93
  _PROFILEBATCHONLINETIMERESPONSE._serialized_end=198
# @@protoc_insertion_point(module_scope)
