# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProfileBatchOnlineTimeRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import User_pb2 as User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ProfileBatchOnlineTimeRequest.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Profile\x1a\nUser.proto\"H\n\x1dProfileBatchOnlineTimeRequest\x12\'\n\x04user\x18\x01 \x03(\x0b\x32\x19.AcFunDanmu.Im.Basic.Userb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProfileBatchOnlineTimeRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROFILEBATCHONLINETIMEREQUEST._serialized_start=80
  _PROFILEBATCHONLINETIMEREQUEST._serialized_end=152
# @@protoc_insertion_point(module_scope)
