# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendMessageResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SendMessageResponse.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\"\xb4\x01\n\x13SendMessageResponse\x12\x13\n\x0b\x63lientSeqId\x18\x01 \x01(\x03\x12\x18\n\x10messageTimestamp\x18\x02 \x01(\x03\x12\r\n\x05seqId\x18\x03 \x01(\x03\x12\x1a\n\x12sessionAccountType\x18\x04 \x01(\x05\x12\x17\n\x0fsessionPriority\x18\x05 \x01(\x05\x12\x19\n\x11sessionCategoryId\x18\x06 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SendMessageResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDMESSAGERESPONSE._serialized_start=53
  _SENDMESSAGERESPONSE._serialized_end=233
# @@protoc_insertion_point(module_scope)
