# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionFolderSortResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SessionFolderBasic_pb2 as SessionFolderBasic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSessionFolderSortResponse.proto\x12!AcFunDanmu.Im.Cloud.SessionFolder\x1a\x18SessionFolderBasic.proto\"i\n\x19SessionFolderSortResponse\x12L\n\rsessionFolder\x18\x01 \x03(\x0b\x32\x35.AcFunDanmu.Im.Cloud.SessionFolder.SessionFolderBasicb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SessionFolderSortResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSIONFOLDERSORTRESPONSE._serialized_start=96
  _SESSIONFOLDERSORTRESPONSE._serialized_end=201
# @@protoc_insertion_point(module_scope)
