# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionReferenceUpdateItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SessionReference_pb2 as SessionReference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SessionReferenceUpdateItem.proto\x12!AcFunDanmu.Im.Cloud.SessionFolder\x1a\x16SessionReference.proto\"\x84\x01\n\x1aSessionReferenceUpdateItem\x12M\n\x10sessionReference\x18\x01 \x01(\x0b\x32\x33.AcFunDanmu.Im.Cloud.SessionFolder.SessionReference\x12\x17\n\x0fsessionFolderId\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SessionReferenceUpdateItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSIONREFERENCEUPDATEITEM._serialized_start=96
  _SESSIONREFERENCEUPDATEITEM._serialized_end=228
# @@protoc_insertion_point(module_scope)
