# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserGroupGetResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UserGroupInfo_pb2 as UserGroupInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aUserGroupGetResponse.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x13UserGroupInfo.proto\"Y\n\x14UserGroupGetResponse\x12\x41\n\ruserGroupInfo\x18\x01 \x03(\x0b\x32*.AcFunDanmu.Im.Cloud.Message.UserGroupInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserGroupGetResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERGROUPGETRESPONSE._serialized_start=80
  _USERGROUPGETRESPONSE._serialized_end=169
# @@protoc_insertion_point(module_scope)
