# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AcceptVoiceCallResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x41\x63\x63\x65ptVoiceCallResponse.proto\x12\x1e\x41\x63\x46unDanmu.Im.Cloud.Voice.Call\"-\n\x17\x41\x63\x63\x65ptVoiceCallResponse\x12\x12\n\nsignalData\x18\x01 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AcceptVoiceCallResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCEPTVOICECALLRESPONSE._serialized_start=65
  _ACCEPTVOICECALLRESPONSE._serialized_end=110
# @@protoc_insertion_point(module_scope)
