# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: B2CMessageReceiptRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import B2CMessageReceiptInfo_pb2 as B2CMessageReceiptInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x42\x32\x43MessageReceiptRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x1b\x42\x32\x43MessageReceiptInfo.proto\"y\n\x18\x42\x32\x43MessageReceiptRequest\x12H\n\x12messageReceiptInfo\x18\x01 \x03(\x0b\x32,.AcFunDanmu.Im.Message.B2CMessageReceiptInfo\x12\x13\n\x0bstrTargetId\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'B2CMessageReceiptRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B2CMESSAGERECEIPTREQUEST._serialized_start=86
  _B2CMESSAGERECEIPTREQUEST._serialized_end=207
# @@protoc_insertion_point(module_scope)
