# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: B2CPullOldRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x42\x32\x43PullOldRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\"W\n\x11\x42\x32\x43PullOldRequest\x12\x13\n\x0bstrTargetId\x18\x01 \x01(\t\x12\x0e\n\x06minSeq\x18\x02 \x01(\x03\x12\x0e\n\x06maxSeq\x18\x03 \x01(\x03\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'B2CPullOldRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B2CPULLOLDREQUEST._serialized_start=50
  _B2CPULLOLDREQUEST._serialized_end=137
# @@protoc_insertion_point(module_scope)
