# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BasicWithMsgSearchRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x42\x61sicWithMsgSearchRequest.proto\x12\x1a\x41\x63\x46unDanmu.Im.Cloud.Search\"F\n\x19\x42\x61sicWithMsgSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x1a\n\x12msgCountPerSession\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BasicWithMsgSearchRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BASICWITHMSGSEARCHREQUEST._serialized_start=63
  _BASICWITHMSGSEARCHREQUEST._serialized_end=133
# @@protoc_insertion_point(module_scope)
