# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BatchGetMessageClickStatusResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ClickStatus_pb2 as ClickStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(BatchGetMessageClickStatusResponse.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x11\x43lickStatus.proto\"]\n\"BatchGetMessageClickStatusResponse\x12\x37\n\x0b\x63lickStatus\x18\x01 \x03(\x0b\x32\".AcFunDanmu.Im.Message.ClickStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BatchGetMessageClickStatusResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BATCHGETMESSAGECLICKSTATUSRESPONSE._serialized_start=86
  _BATCHGETMESSAGECLICKSTATUSRESPONSE._serialized_end=179
# @@protoc_insertion_point(module_scope)
