# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CallParam.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43\x61llParam.proto\x12\x1e\x41\x63\x46unDanmu.Im.Cloud.Voice.Call\"P\n\tCallParam\x12\x0f\n\x07microOn\x18\x01 \x01(\x08\x12\x11\n\tspeakerOn\x18\x02 \x01(\x08\x12\x10\n\x08\x63\x61meraOn\x18\x03 \x01(\x08\x12\r\n\x05\x65xtra\x18\x04 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CallParam_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLPARAM._serialized_start=51
  _CALLPARAM._serialized_end=131
# @@protoc_insertion_point(module_scope)
