# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelBasicInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43hannelBasicInfo.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Channel\">\n\x10\x43hannelBasicInfo\x12\x11\n\tchannelId\x18\x01 \x01(\t\x12\x17\n\x0fsubscriberCount\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelBasicInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELBASICINFO._serialized_start=55
  _CHANNELBASICINFO._serialized_end=117
# @@protoc_insertion_point(module_scope)
