# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelHeartbeatResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x43hannelHeartbeatResponse.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Channel\"5\n\x18\x43hannelHeartbeatResponse\x12\x19\n\x11notExistChannelId\x18\x01 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelHeartbeatResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANNELHEARTBEATRESPONSE._serialized_start=63
  _CHANNELHEARTBEATRESPONSE._serialized_end=116
# @@protoc_insertion_point(module_scope)
