# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForwardMessageContent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Message_pb2 as Message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x46orwardMessageContent.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\rMessage.proto\"W\n\x15\x46orwardMessageContent\x12/\n\x07message\x18\x01 \x03(\x0b\x32\x1e.AcFunDanmu.Im.Message.Message\x12\r\n\x05title\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ForwardMessageContent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FORWARDMESSAGECONTENT._serialized_start=75
  _FORWARDMESSAGECONTENT._serialized_end=162
# @@protoc_insertion_point(module_scope)
