# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetVoiceCallDetailRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fGetVoiceCallDetailRequest.proto\x12\x1e\x41\x63\x46unDanmu.Im.Cloud.Voice.Call\"+\n\x19GetVoiceCallDetailRequest\x12\x0e\n\x06roomId\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetVoiceCallDetailRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETVOICECALLDETAILREQUEST._serialized_start=67
  _GETVOICECALLDETAILREQUEST._serialized_end=110
# @@protoc_insertion_point(module_scope)
