# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupCreateResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GroupInfo_pb2 as GroupInfo__pb2
import GroupMember_pb2 as GroupMember__pb2
import SyncCookie_pb2 as SyncCookie__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19GroupCreateResponse.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x0fGroupInfo.proto\x1a\x11GroupMember.proto\x1a\x10SyncCookie.proto\"\xd1\x01\n\x13GroupCreateResponse\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x39\n\tgroupInfo\x18\x02 \x01(\x0b\x32&.AcFunDanmu.Im.Cloud.Message.GroupInfo\x12\x39\n\x07members\x18\x03 \x03(\x0b\x32(.AcFunDanmu.Im.Cloud.Message.GroupMember\x12\x33\n\nsyncCookie\x18\x04 \x01(\x0b\x32\x1f.AcFunDanmu.Im.Basic.SyncCookieb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupCreateResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPCREATERESPONSE._serialized_start=113
  _GROUPCREATERESPONSE._serialized_end=322
# @@protoc_insertion_point(module_scope)
