# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupSettingMemberTempSilence.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import User_pb2 as User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#GroupSettingMemberTempSilence.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\nUser.proto\"p\n\x1dGroupSettingMemberTempSilence\x12\x0e\n\x06isMute\x18\x01 \x01(\x08\x12\'\n\x04user\x18\x02 \x01(\x0b\x32\x19.AcFunDanmu.Im.Basic.User\x12\x16\n\x0eslienceSeconds\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupSettingMemberTempSilence_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPSETTINGMEMBERTEMPSILENCE._serialized_start=80
  _GROUPSETTINGMEMBERTEMPSILENCE._serialized_end=192
# @@protoc_insertion_point(module_scope)
