# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupJoinRequestCancelResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import JoinRequestStatus_pb2 as JoinRequestStatus__pb2
import User_pb2 as User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$GroupJoinRequestCancelResponse.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x17JoinRequestStatus.proto\x1a\nUser.proto\"\xf0\x01\n\x1eGroupJoinRequestCancelResponse\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12*\n\x07inviter\x18\x02 \x01(\x0b\x32\x19.AcFunDanmu.Im.Basic.User\x12+\n\x08invitees\x18\x03 \x03(\x0b\x32\x19.AcFunDanmu.Im.Basic.User\x12\x0f\n\x07\x66indWay\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scContent\x18\x05 \x01(\t\x12>\n\x06status\x18\x06 \x01(\x0e\x32..AcFunDanmu.Im.Cloud.Message.JoinRequestStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupJoinRequestCancelResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPJOINREQUESTCANCELRESPONSE._serialized_start=107
  _GROUPJOINREQUESTCANCELRESPONSE._serialized_end=347
# @@protoc_insertion_point(module_scope)
