# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fGroupType.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message*;\n\tGroupType\x12\x15\n\x11UNKNOW_GROUP_TYPE\x10\x00\x12\x0b\n\x07PRIVATE\x10\x03\x12\n\n\x06PUBLIC\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUPTYPE._serialized_start=48
  _GROUPTYPE._serialized_end=107
# @@protoc_insertion_point(module_scope)
