# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HandshakeResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17HandshakeResponse.proto\x12\x13\x41\x63\x46unDanmu.Im.Basic\"7\n\x11HansshakeResponse\x12\x10\n\x08unknown1\x18\x01 \x01(\x07\x12\x10\n\x08unknown2\x18\x02 \x01(\x07\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HandshakeResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HANSSHAKERESPONSE._serialized_start=48
  _HANSSHAKERESPONSE._serialized_end=103
# @@protoc_insertion_point(module_scope)
