# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: I18nCopyWriting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15I18nCopyWriting.proto\x12\x13\x41\x63\x46unDanmu.Im.Basic\"9\n\x0fI18nCopyWriting\x12\x11\n\tformatKey\x18\x01 \x01(\t\x12\x13\n\x0b\x66ormatParam\x18\x02 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'I18nCopyWriting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _I18NCOPYWRITING._serialized_start=46
  _I18NCOPYWRITING._serialized_end=103
# @@protoc_insertion_point(module_scope)
