# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImcPassThroughRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatTarget_pb2 as ChatTarget__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bImcPassThroughRequest.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x10\x43hatTarget.proto\"t\n\x15ImcPassThroughRequest\x12\x35\n\nchatTarget\x18\x01 \x01(\x0b\x32!.AcFunDanmu.Im.Message.ChatTarget\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x13\n\x0b\x63ontentType\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ImcPassThroughRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMCPASSTHROUGHREQUEST._serialized_start=78
  _IMCPASSTHROUGHREQUEST._serialized_end=194
# @@protoc_insertion_point(module_scope)
