# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImcPassThroughPush.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatTarget_pb2 as ChatTarget__pb2
import User_pb2 as User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ImcPassThroughPush.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\x10\x43hatTarget.proto\x1a\nUser.proto\"\x9e\x01\n\x12ImcPassThroughPush\x12\x35\n\nchatTarget\x18\x01 \x01(\x0b\x32!.AcFunDanmu.Im.Message.ChatTarget\x12+\n\x08\x66romUser\x18\x02 \x01(\x0b\x32\x19.AcFunDanmu.Im.Basic.User\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x13\n\x0b\x63ontentType\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ImcPassThroughPush_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMCPASSTHROUGHPUSH._serialized_start=88
  _IMCPASSTHROUGHPUSH._serialized_end=246
# @@protoc_insertion_point(module_scope)
