# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImcReplaceMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Message_pb2 as Message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ImcReplaceMessage.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\x1a\rMessage.proto\"h\n\x11ImcReplaceMessage\x12\x32\n\nreplaceMsg\x18\x01 \x01(\x0b\x32\x1e.AcFunDanmu.Im.Message.Message\x12\x1f\n\x17originMsgNotCountUnread\x18\x02 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ImcReplaceMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMCREPLACEMESSAGE._serialized_start=71
  _IMCREPLACEMESSAGE._serialized_end=175
# @@protoc_insertion_point(module_scope)
