# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InvitePermissionType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aInvitePermissionType.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message*X\n\x14InvitePermissionType\x12\"\n\x1eUNKNOWN_INVITE_PERMISSION_TYPE\x10\x00\x12\x0c\n\x08\x45VERYONE\x10\x01\x12\x0e\n\nONLY_ADMIN\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InvitePermissionType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVITEPERMISSIONTYPE._serialized_start=59
  _INVITEPERMISSIONTYPE._serialized_end=147
# @@protoc_insertion_point(module_scope)
