# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JoinRequestStatus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17JoinRequestStatus.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message*f\n\x11JoinRequestStatus\x12\x12\n\x0eUNKNOWN_STATUS\x10\x00\x12\r\n\tREQUESTED\x10\x01\x12\x0c\n\x08\x41PPROVED\x10\x02\x12\x0b\n\x07REFUSED\x10\x03\x12\x13\n\x0fREQUEST_INVALID\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'JoinRequestStatus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINREQUESTSTATUS._serialized_start=56
  _JOINREQUESTSTATUS._serialized_end=158
# @@protoc_insertion_point(module_scope)
