# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeepAliveResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AccessPointsConfig_pb2 as AccessPointsConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17KeepAliveResponse.proto\x12\x13\x41\x63\x46unDanmu.Im.Basic\x1a\x18\x41\x63\x63\x65ssPointsConfig.proto\"\x92\x03\n\x11KeepAliveResponse\x12\x43\n\x12\x61\x63\x63\x65ssPointsConfig\x18\x01 \x01(\x0b\x32\'.AcFunDanmu.Im.Basic.AccessPointsConfig\x12\x12\n\nserverMsec\x18\x02 \x01(\x03\x12G\n\x16\x61\x63\x63\x65ssPointsConfigIpv6\x18\x03 \x01(\x0b\x32\'.AcFunDanmu.Im.Basic.AccessPointsConfig\x12G\n\x16\x61\x63\x63\x65ssPointsConfigQuic\x18\x06 \x01(\x0b\x32\'.AcFunDanmu.Im.Basic.AccessPointsConfig\x12K\n\x1a\x61\x63\x63\x65ssPointsConfigQuicIpv6\x18\x07 \x01(\x0b\x32\'.AcFunDanmu.Im.Basic.AccessPointsConfig\x12\x45\n\x14\x61\x63\x63\x65ssPointsConfigWs\x18\x08 \x01(\x0b\x32\'.AcFunDanmu.Im.Basic.AccessPointsConfigb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KeepAliveResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEEPALIVERESPONSE._serialized_start=75
  _KEEPALIVERESPONSE._serialized_end=477
# @@protoc_insertion_point(module_scope)
