# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KsUserRelationShip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18KsUserRelationShip.proto\x12\x15\x41\x63\x46unDanmu.Im.Message*`\n\x12KsUserRelationShip\x12\x0b\n\x07kUNKNOW\x10\x00\x12\x15\n\x11\x46OLLOW_EACH_OTHER\x10\x01\x12\x12\n\x0eTO_FOLLOW_FROM\x10\x02\x12\x12\n\x0e\x46ROM_FOLLOW_TO\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KsUserRelationShip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KSUSERRELATIONSHIP._serialized_start=51
  _KSUSERRELATIONSHIP._serialized_end=147
# @@protoc_insertion_point(module_scope)
