# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageReceiptDetailGetResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import User_pb2 as User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%MessageReceiptDetailGetResponse.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\nUser.proto\"}\n\x1fMessageReceiptDetailGetResponse\x12+\n\x08readUser\x18\x01 \x03(\x0b\x32\x19.AcFunDanmu.Im.Basic.User\x12-\n\nunreadUser\x18\x02 \x03(\x0b\x32\x19.AcFunDanmu.Im.Basic.Userb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageReceiptDetailGetResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGERECEIPTDETAILGETRESPONSE._serialized_start=76
  _MESSAGERECEIPTDETAILGETRESPONSE._serialized_end=201
# @@protoc_insertion_point(module_scope)
