# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageReceiveStatusSettingRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatTarget_pb2 as ChatTarget__pb2
import MessageReceiveStatus_pb2 as MessageReceiveStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(MessageReceiveStatusSettingRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x10\x43hatTarget.proto\x1a\x1aMessageReceiveStatus.proto\"\x98\x01\n\"MessageReceiveStatusSettingRequest\x12\x35\n\nchatTarget\x18\x01 \x01(\x0b\x32!.AcFunDanmu.Im.Message.ChatTarget\x12;\n\x06status\x18\x02 \x01(\x0e\x32+.AcFunDanmu.Im.Message.MessageReceiveStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageReceiveStatusSettingRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGERECEIVESTATUSSETTINGREQUEST._serialized_start=114
  _MESSAGERECEIVESTATUSSETTINGREQUEST._serialized_end=266
# @@protoc_insertion_point(module_scope)
