# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageSearchResult.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatTarget_pb2 as ChatTarget__pb2
import Message_pb2 as Message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19MessageSearchResult.proto\x12\x1a\x41\x63\x46unDanmu.Im.Cloud.Search\x1a\x10\x43hatTarget.proto\x1a\rMessage.proto\"y\n\x13MessageSearchResult\x12\x35\n\nchatTarget\x18\x01 \x01(\x0b\x32!.AcFunDanmu.Im.Message.ChatTarget\x12+\n\x03msg\x18\x02 \x01(\x0b\x32\x1e.AcFunDanmu.Im.Message.Messageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageSearchResult_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGESEARCHRESULT._serialized_start=90
  _MESSAGESEARCHRESULT._serialized_end=211
# @@protoc_insertion_point(module_scope)
