# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageReceiptRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatTarget_pb2 as ChatTarget__pb2
import MessageReceiptInfo_pb2 as MessageReceiptInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bMessageReceiptRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x10\x43hatTarget.proto\x1a\x18MessageReceiptInfo.proto\"\x95\x01\n\x15MessageReceiptRequest\x12\x45\n\x12messageReceiptInfo\x18\x01 \x03(\x0b\x32).AcFunDanmu.Im.Message.MessageReceiptInfo\x12\x35\n\nchatTarget\x18\x02 \x01(\x0b\x32!.AcFunDanmu.Im.Message.ChatTargetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageReceiptRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGERECEIPTREQUEST._serialized_start=99
  _MESSAGERECEIPTREQUEST._serialized_end=248
# @@protoc_insertion_point(module_scope)
