# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PullOldRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import User_pb2 as User__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PullOldRequest.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\nUser.proto\"\x91\x01\n\x0ePullOldRequest\x12)\n\x06target\x18\x01 \x01(\x0b\x32\x19.AcFunDanmu.Im.Basic.User\x12\x0e\n\x06minSeq\x18\x02 \x01(\x03\x12\x0e\n\x06maxSeq\x18\x03 \x01(\x03\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\x12\x10\n\x08targetId\x18\x05 \x01(\x03\x12\x13\n\x0bstrTargetId\x18\x06 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PullOldRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PULLOLDREQUEST._serialized_start=60
  _PULLOLDREQUEST._serialized_end=205
# @@protoc_insertion_point(module_scope)
