# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Reminder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RemindBody_pb2 as RemindBody__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eReminder.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x10RemindBody.proto\"U\n\x08Reminder\x12\x12\n\noriginText\x18\x01 \x01(\t\x12\x35\n\nremindBody\x18\x02 \x03(\x0b\x32!.AcFunDanmu.Im.Message.RemindBodyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Reminder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REMINDER._serialized_start=59
  _REMINDER._serialized_end=144
# @@protoc_insertion_point(module_scope)
