# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RichTextMessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RichTextNoticeMessage_pb2 as RichTextNoticeMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RichTextMessage.proto\x12\x15\x41\x63\x46unDanmu.Im.Message\x1a\x1bRichTextNoticeMessage.proto\"X\n\x0fRichTextMessage\x12\x45\n\x0frichTextMessage\x18\x01 \x01(\x0b\x32,.AcFunDanmu.Im.Message.RichTextNoticeMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RichTextMessage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RICHTEXTMESSAGE._serialized_start=77
  _RICHTEXTMESSAGE._serialized_end=165
# @@protoc_insertion_point(module_scope)
