# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionFolderBasic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18SessionFolderBasic.proto\x12!AcFunDanmu.Im.Cloud.SessionFolder\"\x84\x01\n\x12SessionFolderBasic\x12\x17\n\x0fsessionFolderId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65xtra\x18\x03 \x01(\x0c\x12\x0f\n\x07\x64\x65leted\x18\x04 \x01(\x08\x12\x0f\n\x07iconUrl\x18\x05 \x01(\t\x12\x16\n\x0e\x66olderPriority\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SessionFolderBasic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSIONFOLDERBASIC._serialized_start=64
  _SESSIONFOLDERBASIC._serialized_end=196
# @@protoc_insertion_point(module_scope)
