# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionFolderBatchDeleteRefRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SessionReference_pb2 as SessionReference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(SessionFolderBatchDeleteRefRequest.proto\x12!AcFunDanmu.Im.Cloud.SessionFolder\x1a\x16SessionReference.proto\"\x92\x01\n\"SessionFolderBatchDeleteRefRequest\x12M\n\x10sessionReference\x18\x01 \x01(\x0b\x32\x33.AcFunDanmu.Im.Cloud.SessionFolder.SessionReference\x12\x1d\n\x15targetSessionFolderId\x18\x02 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SessionFolderBatchDeleteRefRequest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSIONFOLDERBATCHDELETEREFREQUEST._serialized_start=104
  _SESSIONFOLDERBATCHDELETEREFREQUEST._serialized_end=250
# @@protoc_insertion_point(module_scope)
