# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SessionAggregationType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSessionAggregationType.proto\x12\x15\x41\x63\x46unDanmu.Im.Message*]\n\x16SessionAggregationType\x12\x1c\n\x18UNKNOWN_AGGREGATION_TYPE\x10\x00\x12\r\n\tAGGREGATE\x10\x01\x12\x16\n\x12\x43\x41NCEL_AGGREGATION\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SessionAggregationType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SESSIONAGGREGATIONTYPE._serialized_start=55
  _SESSIONAGGREGATIONTYPE._serialized_end=148
# @@protoc_insertion_point(module_scope)
