# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetUserAntiDisturbing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSetUserAntiDisturbing.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Message\"/\n\x15SetUserAntiDisturbing\x12\x16\n\x0e\x61ntiDisturbing\x18\x01 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetUserAntiDisturbing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETUSERANTIDISTURBING._serialized_start=60
  _SETUSERANTIDISTURBING._serialized_end=107
# @@protoc_insertion_point(module_scope)
