# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SixinCustomPushPayload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SixinCustomPushType_pb2 as SixinCustomPushType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSixinCustomPushPayload.proto\x12\x1f\x41\x63\x46unDanmu.Im.Cloud.Data.Update\x1a\x19SixinCustomPushType.proto\"m\n\x16SixinCustomPushPayload\x12\x42\n\x04type\x18\x01 \x01(\x0e\x32\x34.AcFunDanmu.Im.Cloud.Data.Update.SixinCustomPushType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SixinCustomPushPayload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIXINCUSTOMPUSHPAYLOAD._serialized_start=92
  _SIXINCUSTOMPUSHPAYLOAD._serialized_end=201
# @@protoc_insertion_point(module_scope)
