# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10UserAction.proto\x12\x1b\x41\x63\x46unDanmu.Im.Cloud.Channel*e\n\nUserAction\x12\x17\n\x13USER_ACTION_UNKNOWN\x10\x00\x12\x15\n\x11USER_JOIN_CHANNEL\x10\x01\x12\x15\n\x11USER_QUIT_CHANNEL\x10\x02\x12\x10\n\x0cUSER_OFFLINE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserAction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERACTION._serialized_start=49
  _USERACTION._serialized_end=150
# @@protoc_insertion_point(module_scope)
