# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VoiceCallDetailUpdateEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import VoiceCallDetail_pb2 as VoiceCallDetail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n VoiceCallDetailUpdateEvent.proto\x12\x1e\x41\x63\x46unDanmu.Im.Cloud.Voice.Call\x1a\x15VoiceCallDetail.proto\"f\n\x1aVoiceCallDetailUpdateEvent\x12H\n\x0fvoiceCallDetail\x18\x01 \x01(\x0b\x32/.AcFunDanmu.Im.Cloud.Voice.Call.VoiceCallDetailb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VoiceCallDetailUpdateEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOICECALLDETAILUPDATEEVENT._serialized_start=91
  _VOICECALLDETAILUPDATEEVENT._serialized_end=193
# @@protoc_insertion_point(module_scope)
