# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AccessPointsConfig.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AccessPoint_pb2 as AccessPoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41\x63\x63\x65ssPointsConfig.proto\x12\nAcFunDanmu\x1a\x11\x41\x63\x63\x65ssPoint.proto\"\xbd\x01\n\x12\x41\x63\x63\x65ssPointsConfig\x12+\n\noptimalAps\x18\x01 \x03(\x0b\x32\x17.AcFunDanmu.AccessPoint\x12*\n\tbackupAps\x18\x02 \x03(\x0b\x32\x17.AcFunDanmu.AccessPoint\x12\x16\n\x0e\x61vailablePorts\x18\x03 \x03(\r\x12\x36\n\x15\x66oreceLastConnectedAp\x18\x04 \x01(\x0b\x32\x17.AcFunDanmu.AccessPointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AccessPointsConfig_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCESSPOINTSCONFIG._serialized_start=60
  _ACCESSPOINTSCONFIG._serialized_end=249
# @@protoc_insertion_point(module_scope)
