# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthorChatPlayerInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ZtLiveUserInfo_pb2 as ZtLiveUserInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x41uthorChatPlayerInfo.proto\x12\nAcFunDanmu\x1a\x14ZtLiveUserInfo.proto\"r\n\x14\x41uthorChatPlayerInfo\x12*\n\x06player\x18\x01 \x01(\x0b\x32\x1a.AcFunDanmu.ZtLiveUserInfo\x12\x0e\n\x06liveId\x18\x02 \x01(\t\x12\x1e\n\x16\x65nableJumpPeerLiveRoom\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AuthorChatPlayerInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHORCHATPLAYERINFO._serialized_start=64
  _AUTHORCHATPLAYERINFO._serialized_end=178
# @@protoc_insertion_point(module_scope)
