# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonStateSignalPKSoundConfigChanged.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+CommonStateSignalPKSoundConfigChanged.proto\x12\nAcFunDanmu\"\x98\x01\n%CommonStateSignalPKSoundConfigChanged\x12\t\n\x01\x61\x18\x01 \x01(\t\x12\x44\n\x01\x62\x18\x02 \x01(\x0e\x32\x39.AcFunDanmu.CommonStateSignalPKSoundConfigChanged.unknown\"\x1e\n\x07unknown\x12\x05\n\x01\x63\x10\x00\x12\x05\n\x01\x64\x10\x01\x12\x05\n\x01\x65\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommonStateSignalPKSoundConfigChanged_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONSTATESIGNALPKSOUNDCONFIGCHANGED._serialized_start=60
  _COMMONSTATESIGNALPKSOUNDCONFIGCHANGED._serialized_end=212
  _COMMONSTATESIGNALPKSOUNDCONFIGCHANGED_UNKNOWN._serialized_start=182
  _COMMONSTATESIGNALPKSOUNDCONFIGCHANGED_UNKNOWN._serialized_end=212
# @@protoc_insertion_point(module_scope)
