# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeepAlive.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Register_pb2 as Register__pb2
import PushServiceToken_pb2 as PushServiceToken__pb2
import AccessPointsConfig_pb2 as AccessPointsConfig__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fKeepAlive.proto\x12\nAcFunDanmu\x1a\x0eRegister.proto\x1a\x16PushServiceToken.proto\x1a\x18\x41\x63\x63\x65ssPointsConfig.proto\"\xab\x02\n\x10KeepAliveRequest\x12\x42\n\x0epresenceStatus\x18\x01 \x01(\x0e\x32*.AcFunDanmu.RegisterRequest.PresenceStatus\x12\x41\n\x0f\x61ppActiveStatus\x18\x02 \x01(\x0e\x32(.AcFunDanmu.RegisterRequest.ActiveStatus\x12\x36\n\x10pushServiceToken\x18\x03 \x01(\x0b\x32\x1c.AcFunDanmu.PushServiceToken\x12:\n\x14pushServiceTokenList\x18\x04 \x03(\x0b\x32\x1c.AcFunDanmu.PushServiceToken\x12\x1c\n\x14keepaliveIntervalSec\x18\x05 \x01(\x05\"\xa3\x01\n\x11KeepAliveResponse\x12:\n\x12\x61\x63\x63\x65ssPointsConfig\x18\x01 \x01(\x0b\x32\x1e.AcFunDanmu.AccessPointsConfig\x12\x12\n\nserverMsec\x18\x02 \x01(\x03\x12>\n\x16\x61\x63\x63\x65ssPointsConfigIpv6\x18\x03 \x01(\x0b\x32\x1e.AcFunDanmu.AccessPointsConfigb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KeepAlive_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEEPALIVEREQUEST._serialized_start=98
  _KEEPALIVEREQUEST._serialized_end=397
  _KEEPALIVERESPONSE._serialized_start=400
  _KEEPALIVERESPONSE._serialized_end=563
# @@protoc_insertion_point(module_scope)
