# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KwaiStateSignalEcommerceCart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"KwaiStateSignalEcommerceCart.proto\x12\nAcFunDanmu\"t\n\x1cKwaiStateSignalEcommerceCart\x12;\n\x01\x61\x18\x01 \x01(\x0e\x32\x30.AcFunDanmu.KwaiStateSignalEcommerceCart.unknown\"\x17\n\x07unknown\x12\x05\n\x01\x62\x10\x00\x12\x05\n\x01\x63\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KwaiStateSignalEcommerceCart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KWAISTATESIGNALECOMMERCECART._serialized_start=50
  _KWAISTATESIGNALECOMMERCECART._serialized_end=166
  _KWAISTATESIGNALECOMMERCECART_UNKNOWN._serialized_start=143
  _KWAISTATESIGNALECOMMERCECART_UNKNOWN._serialized_end=166
# @@protoc_insertion_point(module_scope)
