# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Ping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nPing.proto\x12\nAcFunDanmu\"\x95\x01\n\x0bPingRequest\x12\x32\n\x08pingType\x18\x01 \x01(\x0e\x32 .AcFunDanmu.PingRequest.PingType\x12\x11\n\tpingRound\x18\x02 \x01(\r\"?\n\x08PingType\x12\x0c\n\x08kInvalid\x10\x00\x12\x12\n\x0ekPriorRegister\x10\x01\x12\x11\n\rkPostRegister\x10\x02\"c\n\x0cPingResponse\x12\x17\n\x0fserverTimestamp\x18\x01 \x01(\x0f\x12\x10\n\x08\x63lientIp\x18\x02 \x01(\x07\x12\x12\n\nredirectIp\x18\x03 \x01(\x07\x12\x14\n\x0credirectPort\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Ping_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PINGREQUEST._serialized_start=27
  _PINGREQUEST._serialized_end=176
  _PINGREQUEST_PINGTYPE._serialized_start=113
  _PINGREQUEST_PINGTYPE._serialized_end=176
  _PINGRESPONSE._serialized_start=178
  _PINGRESPONSE._serialized_end=277
# @@protoc_insertion_point(module_scope)
