# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PkPlayerStatistic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ZtLiveUserInfo_pb2 as ZtLiveUserInfo__pb2
import PkPlayerRoundStatistic_pb2 as PkPlayerRoundStatistic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PkPlayerStatistic.proto\x12\nAcFunDanmu\x1a\x14ZtLiveUserInfo.proto\x1a\x1cPkPlayerRoundStatistic.proto\"\x8a\x01\n\x11PkPlayerStatistic\x12%\n\x01\x61\x18\x01 \x01(\x0b\x32\x1a.AcFunDanmu.ZtLiveUserInfo\x12\t\n\x01\x62\x18\x02 \x01(\t\x12\t\n\x01\x63\x18\x03 \x01(\x03\x12-\n\x01\x64\x18\x04 \x03(\x0b\x32\".AcFunDanmu.PkPlayerRoundStatistic\x12\t\n\x01\x65\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PkPlayerStatistic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PKPLAYERSTATISTIC._serialized_start=92
  _PKPLAYERSTATISTIC._serialized_end=230
# @@protoc_insertion_point(module_scope)
