# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Unregister.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Unregister.proto\x12\nAcFunDanmu\"\x13\n\x11UnregisterRequest\"\x14\n\x12UnregisterResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unregister_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNREGISTERREQUEST._serialized_start=32
  _UNREGISTERREQUEST._serialized_end=51
  _UNREGISTERRESPONSE._serialized_start=53
  _UNREGISTERRESPONSE._serialized_end=73
# @@protoc_insertion_point(module_scope)
