# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ZtLiveScNotifySignal.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ZtLiveNotifySignalItem_pb2 as ZtLiveNotifySignalItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aZtLiveScNotifySignal.proto\x12\nAcFunDanmu\x1a\x1cZtLiveNotifySignalItem.proto\"H\n\x14ZtLiveScNotifySignal\x12\x30\n\x04item\x18\x01 \x03(\x0b\x32\".AcFunDanmu.ZtLiveNotifySignalItemb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ZtLiveScNotifySignal_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZTLIVESCNOTIFYSIGNAL._serialized_start=72
  _ZTLIVESCNOTIFYSIGNAL._serialized_end=144
# @@protoc_insertion_point(module_scope)
