# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonActionSignalComment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ZtLiveUserInfo_pb2 as ZtLiveUserInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43ommonActionSignalComment.proto\x12\nAcFunDanmu\x1a\x14ZtLiveUserInfo.proto\"n\n\x19\x43ommonActionSignalComment\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x12\n\nsendTimeMs\x18\x02 \x01(\x03\x12,\n\x08userInfo\x18\x03 \x01(\x0b\x32\x1a.AcFunDanmu.ZtLiveUserInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommonActionSignalComment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONACTIONSIGNALCOMMENT._serialized_start=69
  _COMMONACTIONSIGNALCOMMENT._serialized_end=179
# @@protoc_insertion_point(module_scope)
