# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonStateSignalDisplayInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"CommonStateSignalDisplayInfo.proto\x12\nAcFunDanmu\"[\n\x1c\x43ommonStateSignalDisplayInfo\x12\x15\n\rwatchingCount\x18\x01 \x01(\t\x12\x11\n\tlikeCount\x18\x02 \x01(\t\x12\x11\n\tlikeDelta\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommonStateSignalDisplayInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONSTATESIGNALDISPLAYINFO._serialized_start=50
  _COMMONSTATESIGNALDISPLAYINFO._serialized_end=141
# @@protoc_insertion_point(module_scope)
