# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WidgetDisplayStyle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18WidgetDisplayStyle.proto\x12\nAcFunDanmu\"*\n\x12WidgetDisplayStyle\x12\t\n\x01\x61\x18\x01 \x01(\x08\x12\t\n\x01\x62\x18\x02 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WidgetDisplayStyle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIDGETDISPLAYSTYLE._serialized_start=40
  _WIDGETDISPLAYSTYLE._serialized_end=82
# @@protoc_insertion_point(module_scope)
