# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ZtLiveCsUserExit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ZtLiveCsUserExit.proto\x12\nAcFunDanmu\"\x12\n\x10ZtLiveCsUserExit\"\x15\n\x13ZtLiveCsUserExitAckb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ZtLiveCsUserExit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZTLIVECSUSEREXIT._serialized_start=38
  _ZTLIVECSUSEREXIT._serialized_end=56
  _ZTLIVECSUSEREXITACK._serialized_start=58
  _ZTLIVECSUSEREXITACK._serialized_end=79
# @@protoc_insertion_point(module_scope)
