# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ZtLivePkProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ZtLivePkProto.proto\x12\nAcFunDanmu*_\n\rZtLivePkProto\x12\x12\n\x0eZtLivePkProtoA\x10\x00\x12\x12\n\x0eZtLivePkProtoB\x10\x01\x12\x12\n\x0eZtLivePkProtoC\x10\x02\x12\x12\n\x0eZtLivePkProtoD\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ZtLivePkProto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZTLIVEPKPROTO._serialized_start=35
  _ZTLIVEPKPROTO._serialized_end=130
# @@protoc_insertion_point(module_scope)
