# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BackgroundStyle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ImageCdnNode_pb2 as ImageCdnNode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42\x61\x63kgroundStyle.proto\x12\nAcFunDanmu\x1a\x12ImageCdnNode.proto\"a\n\x0f\x42\x61\x63kgroundStyle\x12\t\n\x01\x61\x18\x01 \x01(\t\x12#\n\x01\x62\x18\x02 \x03(\x0b\x32\x18.AcFunDanmu.ImageCdnNode\"\x1e\n\x07unknown\x12\x05\n\x01\x63\x10\x00\x12\x05\n\x01\x64\x10\x01\x12\x05\n\x01\x65\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BackgroundStyle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BACKGROUNDSTYLE._serialized_start=57
  _BACKGROUNDSTYLE._serialized_end=154
  _BACKGROUNDSTYLE_UNKNOWN._serialized_start=124
  _BACKGROUNDSTYLE_UNKNOWN._serialized_end=154
# @@protoc_insertion_point(module_scope)
