# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Button.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ZtLiveCommonModelProto_pb2 as ZtLiveCommonModelProto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x42utton.proto\x12\nAcFunDanmu\x1a\x1cZtLiveCommonModelProto.proto\"X\n\x06\x42utton\x12\t\n\x01\x61\x18\x01 \x01(\t\x12\t\n\x01\x62\x18\x02 \x01(\t\x12-\n\x01\x63\x18\x03 \x01(\x0e\x32\".AcFunDanmu.ZtLiveCommonModelProto\x12\t\n\x01\x64\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Button_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUTTON._serialized_start=58
  _BUTTON._serialized_end=146
# @@protoc_insertion_point(module_scope)
