# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonStateSignalShoppingCart.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#CommonStateSignalShoppingCart.proto\x12\nAcFunDanmu\"\x88\x01\n\x1d\x43ommonStateSignalShoppingCart\x12<\n\x01\x61\x18\x01 \x01(\x0e\x32\x31.AcFunDanmu.CommonStateSignalShoppingCart.unknown\x12\t\n\x01\x62\x18\x02 \x01(\t\"\x1e\n\x07unknown\x12\x05\n\x01\x63\x10\x00\x12\x05\n\x01\x64\x10\x01\x12\x05\n\x01\x65\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CommonStateSignalShoppingCart_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMONSTATESIGNALSHOPPINGCART._serialized_start=52
  _COMMONSTATESIGNALSHOPPINGCART._serialized_end=188
  _COMMONSTATESIGNALSHOPPINGCART_UNKNOWN._serialized_start=158
  _COMMONSTATESIGNALSHOPPINGCART_UNKNOWN._serialized_end=188
# @@protoc_insertion_point(module_scope)
