# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PkAudienceContributionInfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PkAudienceContributionDetail_pb2 as PkAudienceContributionDetail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n PkAudienceContributionInfo.proto\x12\nAcFunDanmu\x1a\"PkAudienceContributionDetail.proto\"\\\n\x1aPkAudienceContributionInfo\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\x33\n\x01\x62\x18\x02 \x03(\x0b\x32(.AcFunDanmu.PkAudienceContributionDetailb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PkAudienceContributionInfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PKAUDIENCECONTRIBUTIONINFO._serialized_start=84
  _PKAUDIENCECONTRIBUTIONINFO._serialized_end=176
# @@protoc_insertion_point(module_scope)
