# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WidgetItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WidgetDisplayStyle_pb2 as WidgetDisplayStyle__pb2
import WidgetPictureInfo_pb2 as WidgetPictureInfo__pb2
import ZtLiveWidgetProto_pb2 as ZtLiveWidgetProto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10WidgetItem.proto\x12\nAcFunDanmu\x1a\x18WidgetDisplayStyle.proto\x1a\x17WidgetPictureInfo.proto\x1a\x17ZtLiveWidgetProto.proto\"\xc5\x02\n\nWidgetItem\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\t\x12\t\n\x01\x63\x18\x03 \x01(\x05\x12\t\n\x01\x64\x18\x04 \x01(\x03\x12\t\n\x01\x65\x18\x05 \x01(\x03\x12(\n\x01\x66\x18\x06 \x01(\x0b\x32\x1d.AcFunDanmu.WidgetPictureInfo\x12\t\n\x01g\x18\x07 \x01(\t\x12)\n\x01h\x18\x08 \x01(\x0e\x32\x1e.AcFunDanmu.ZtLiveWidgetProtoA\x12)\n\x01i\x18\t \x01(\x0e\x32\x1e.AcFunDanmu.ZtLiveWidgetProtoB\x12)\n\x01j\x18\n \x01(\x0b\x32\x1e.AcFunDanmu.WidgetDisplayStyle\x12)\n\x01k\x18\x0b \x01(\x0e\x32\x1e.AcFunDanmu.ZtLiveWidgetProtoC\x12\t\n\x01l\x18\x0c \x03(\t\x12\t\n\x01m\x18\r \x03(\t\x12\t\n\x01n\x18\x0e \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WidgetItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIDGETITEM._serialized_start=109
  _WIDGETITEM._serialized_end=434
# @@protoc_insertion_point(module_scope)
