# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ZtLiveCommonModelProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cZtLiveCommonModelProto.proto\x12\nAcFunDanmu*o\n\x16ZtLiveCommonModelProto\x12\x1b\n\x17ZtLiveCommonModelProtoA\x10\x00\x12\x1b\n\x17ZtLiveCommonModelProtoB\x10\x01\x12\x1b\n\x17ZtLiveCommonModelProtoC\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ZtLiveCommonModelProto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ZTLIVECOMMONMODELPROTO._serialized_start=44
  _ZTLIVECOMMONMODELPROTO._serialized_end=155
# @@protoc_insertion_point(module_scope)
